/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOpportunitiesRouteImport } from './routes/app.opportunities'
import { Route as AppOrganizationRouteImport } from './routes/app.organization'
import { Route as AppPipelineRouteImport } from './routes/app.pipeline'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppProposalsRouteImport } from './routes/app.proposals'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSupportRouteImport } from './routes/app.support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationRoute = AppOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProposalsRoute = AppProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/proposals': typeof AppProposalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/proposals': typeof AppProposalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/opportunities': typeof AppOpportunitiesRoute
  '/app/organization': typeof AppOrganizationRoute
  '/app/pipeline': typeof AppPipelineRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/proposals': typeof AppProposalsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/ai'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/customers'
    | '/app/documents'
    | '/app/integrations'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/organization'
    | '/app/pipeline'
    | '/app/projects'
    | '/app/proposals'
    | '/app/settings'
    | '/app/support'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/ai'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/customers'
    | '/app/documents'
    | '/app/integrations'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/organization'
    | '/app/pipeline'
    | '/app/projects'
    | '/app/proposals'
    | '/app/settings'
    | '/app/support'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/ai'
    | '/app/analytics'
    | '/app/calendar'
    | '/app/customers'
    | '/app/documents'
    | '/app/integrations'
    | '/app/notifications'
    | '/app/opportunities'
    | '/app/organization'
    | '/app/pipeline'
    | '/app/projects'
    | '/app/proposals'
    | '/app/settings'
    | '/app/support'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opportunities': {
      id: '/app/opportunities'
      path: '/opportunities'
      fullPath: '/app/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organization': {
      id: '/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AppOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proposals': {
      id: '/app/proposals'
      path: '/proposals'
      fullPath: '/app/proposals'
      preLoaderRoute: typeof AppProposalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppOrganizationRoute: typeof AppOrganizationRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppProposalsRoute: typeof AppProposalsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppOrganizationRoute: AppOrganizationRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppProposalsRoute: AppProposalsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
